image: alpine-node:latest

pages:
  stage: deploy
  script:
  - apk add grpc
  - npm i node-sass
  - npx sass src/index.sass public/index.css
  - npx sass src/about.sass public/about.css
  artifacts:
    paths:
    - public
  only:
  - master
