image: node:latest

pages:
  stage: deploy
  script:
  - npm i -g node-sass
  - sass src/index.sass public/index.css
  - sass src/about.sass public/about.css
  artifacts:
    paths:
    - public
  only:
  - master
