image: alpine:latest

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
    
pages:
  stage: deploy
  script:
  - echo 'Deploying...'
  artifacts:
    paths:
    - public
  only:
  - master
