image: node:latest

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
    
variables:
  LC_ALL: C.UTF-8

pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - make build
  artifacts:
    paths:
    - public
  only:
  - master
