title: Eric S. Londres
author: Eric S. Londres
email: elondres@stevens.edu
description: "Eric S. Londres's personal website and blog"
baseurl: ""
url: "https://slondr.ml"

post_dirs: false

exclude:
  - Gemfile

include:
  - .well-known

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Github Flavoerd Markdown
  hard_wrap: false
highlighter: rouge
  
gitlab:
  repository_url: https://gitlab.com/slondr/slondr.gitlab.io
  branch: master

gems:
  - jekyll-feed
  - kramdown
  - rouge
  
